use MovieTVAnalytics;
SELECT * FROM GENRE;

SELECT * FROM USER;
SELECT * FROM MOVIE;
SELECT * FROM TV_SHOW;
SELECT * FROM ACTOR;
SELECT * FROM WATCH_HISTORY;
SELECT * FROM RATING;
SELECT * FROM RECOMMENDATION;
